import Link from "next/link";
import { SiteHeader, Footer } from "@/components/nav";

export const metadata = {
  title: "Privacy Policy | AI Prosperity",
  description: "Privacy policy for AI Prosperity Auto Trades application.",
};

export default function PrivacyPage() {
  return (
    <>
      <SiteHeader />

      <main className="container-x py-12 md:py-20">
        <div className="mx-auto max-w-4xl space-y-12">
          {/* Header */}
          <div className="border-b border-ink-800 pb-8">
            <span className="pill text-gold-400 border-gold-500/40 mb-3">Privacy &amp; Data Protection</span>
            <h1 className="text-3xl font-bold text-white sm:text-5xl">Privacy Policy</h1>
            <p className="mt-3 text-sm text-muted">
              Application: <strong className="text-white">AI Prosperity Auto Trades</strong>
            </p>
          </div>

          <section className="card p-6 md:p-10 space-y-6">
            <p className="text-sm text-muted leading-relaxed">
              This Privacy Policy explains how the Auto Trades application (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) collects, uses, shares, and protects your personal and financial information when you use our mobile/web application and related services.
            </p>

            <div className="space-y-6 text-sm text-muted leading-relaxed">
              <div>
                <h2 className="font-semibold text-white text-lg border-b border-ink-800 pb-2">1. Information We Collect</h2>
                <p className="mt-2">To provide automated trading services, we must collect specific information from you:</p>
                <ul className="list-disc list-inside mt-2 space-y-1.5 pl-2">
                  <li><strong>Account Information:</strong> Name, email address, phone number, and account credentials created for our app.</li>
                  <li><strong>Financial &amp; Trading Data:</strong> Demat account details, broker names, trading history, open positions, and margin balances.</li>
                  <li><strong>API Keys and Access Tokens:</strong> To execute trades automatically, we collect the API keys, secret keys, or OAuth access tokens provided by your broker.</li>
                  <li><strong>Device and Usage Data:</strong> IP address, device type, operating system, and how you interact with our app (logs and crash reports).</li>
                </ul>
              </div>

              <div>
                <h2 className="font-semibold text-white text-lg border-b border-ink-800 pb-2">2. How We Handle Demat API Keys and Credentials</h2>
                <p className="mt-2">The security of your broker API keys is our highest priority.</p>
                <ul className="list-disc list-inside mt-2 space-y-1.5 pl-2">
                  <li><strong>No Primary Passwords:</strong> We do not ask for, nor do we store, the primary login password to your Demat account. We rely strictly on API keys or secure access tokens generated by your broker.</li>
                  <li><strong>Encryption:</strong> All API keys and access tokens are encrypted both in transit (using TLS/SSL) and at rest within our databases using industry-standard encryption protocols.</li>
                  <li><strong>Restricted Access:</strong> Your API keys are used solely by our algorithmic trading engine to execute trades based on the parameters you select. Human staff do not have access to view your unencrypted API keys.</li>
                  <li><strong>Revocation:</strong> You maintain the right to revoke our API access at any time directly through your broker&apos;s dashboard or within our app settings.</li>
                </ul>
              </div>

              <div>
                <h2 className="font-semibold text-white text-lg border-b border-ink-800 pb-2">3. How We Use Your Information</h2>
                <p className="mt-2">We use your data strictly to deliver and improve our services:</p>
                <ul className="list-disc list-inside mt-2 space-y-1.5 pl-2">
                  <li>To connect to your broker and execute automated trades on your behalf.</li>
                  <li>To display your portfolio, trade history, and performance metrics within the app.</li>
                  <li>To send you critical alerts regarding trade executions, errors, or margin requirements.</li>
                  <li>To troubleshoot technical issues and improve the app&apos;s performance and algorithms.</li>
                </ul>
              </div>

              <div>
                <h2 className="font-semibold text-white text-lg border-b border-ink-800 pb-2">4. Data Sharing and Disclosure</h2>
                <p className="mt-2">We do not sell, rent, or trade your personal or financial data. We only share information under the following circumstances:</p>
                <ul className="list-disc list-inside mt-2 space-y-1.5 pl-2">
                  <li><strong>Your Broker:</strong> We transmit necessary data (order details, API tokens) directly to your designated broker to execute trades.</li>
                  <li><strong>Service Providers:</strong> We may use secure third-party cloud hosting and infrastructure providers to operate the app. These providers are bound by strict confidentiality agreements.</li>
                  <li><strong>Legal &amp; Regulatory Obligations:</strong> We may disclose your information if required by law, court order, or a regulatory authority (such as SEBI or other financial regulators).</li>
                </ul>
              </div>

              <div>
                <h2 className="font-semibold text-white text-lg border-b border-ink-800 pb-2">5. Data Security</h2>
                <p className="mt-2">
                  We implement robust technical and organizational measures to protect your data against unauthorized access, loss, or alteration. However, no method of transmission over the internet or electronic storage is 100% secure. You are responsible for keeping your Auto Trades app login credentials confidential and for securing the primary access to your Demat account.
                </p>
              </div>

              <div>
                <h2 className="font-semibold text-white text-lg border-b border-ink-800 pb-2">6. Your Rights and Data Deletion</h2>
                <p className="mt-2">You have the right to access the personal data we hold about you, correct inaccurate information, or request deletion of your account and associated data.</p>
                <p className="mt-2">
                  <strong>Account Deletion:</strong> If you choose to delete your Auto Trades account, we will permanently delete your API keys and access tokens from our active databases. (Note: We may retain certain transaction logs as required by law for compliance and audit purposes).
                </p>
              </div>

              <div>
                <h2 className="font-semibold text-white text-lg border-b border-ink-800 pb-2">7. Governing Law</h2>
                <p className="mt-2">
                  This Privacy Policy shall be governed by and construed in accordance with the laws of India. Any disputes arising from this policy shall be subject to the exclusive jurisdiction of the courts in Nashik, Maharashtra.
                </p>
              </div>
            </div>
          </section>

          <div className="text-center pt-4">
            <Link href="/signup" className="btn-gold px-8 py-3 text-base">
              Back to Signup →
            </Link>
          </div>
        </div>
      </main>

      <Footer />
    </>
  );
}
